# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jiaoliuhuifu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luntanjiaoliuid', models.IntegerField(default=0, verbose_name='论坛交流id')),
                ('bianhao', models.CharField(default='', max_length=50, verbose_name='编号')),
                ('biaoti', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('fenlei', models.IntegerField(default=0, verbose_name='分类')),
                ('faburen', models.CharField(db_column='faburen', default='', max_length=50, verbose_name='发布人')),
                ('jiaoliuneirong', models.TextField(default='', verbose_name='交流内容')),
                ('huifuren', models.CharField(db_column='huifuren', default='', max_length=50, verbose_name='回复人')),
                ('huifuquanxian', models.CharField(default='', max_length=50, verbose_name='回复权限')),
                ('touxiang', models.CharField(default='', max_length=255, verbose_name='头像')),
                ('xingming', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
            ],
            options={
                'verbose_name': '交流回复',
                'verbose_name_plural': '交流回复',
                'db_table': 'jiaoliuhuifu',
            },
        ),
    ]
