# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wenti', models.IntegerField(default=0, verbose_name='问题')),
                ('huidaneirong', models.TextField(default='', verbose_name='回答内容')),
                ('quanzhi', models.IntegerField(default=0, verbose_name='权值')),
                ('huidacishu', models.IntegerField(default=0, verbose_name='回答次数')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'db_table': 'huida',
            },
        ),
    ]
