# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xiaoxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siliaoid', models.IntegerField(default=0, verbose_name='私聊id')),
                ('bianhao', models.CharField(default='', max_length=50, verbose_name='编号')),
                ('neirong', models.TextField(default='', verbose_name='内容')),
                ('fasongren', models.CharField(db_column='fasongren', default='', max_length=50, verbose_name='发送人')),
                ('fasongshijian', models.CharField(default='', max_length=19, verbose_name='发送时间')),
                ('shifouzhakan', models.CharField(default='', max_length=50, verbose_name='是否查看')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'xiaoxi',
            },
        ),
    ]
