# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='课程名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='课程编号')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('category', models.IntegerField(default=0, verbose_name='课程分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Kechengxuexi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kechengxinxiid', models.IntegerField(default=0, verbose_name='课程信息id')),
                ('kechengbianhao', models.CharField(default='', max_length=50, verbose_name='课程编号')),
                ('kechengmingcheng', models.CharField(default='', max_length=255, verbose_name='课程名称')),
                ('kechengfenlei', models.IntegerField(default=0, verbose_name='课程分类')),
                ('fabujiaoshi', models.CharField(db_column='fabujiaoshi', default='', max_length=50, verbose_name='发布教师')),
                ('xuexibianhao', models.CharField(default='', max_length=50, verbose_name='学习编号')),
                ('xuexijindu', models.IntegerField(default=0, verbose_name='学习进度')),
                ('xueshengyonghu', models.CharField(db_column='xueshengyonghu', default='', max_length=50, verbose_name='学生用户')),
                ('xuexizhuangtai', models.CharField(choices=[('待学习', '待学习'), ('学习中', '学习中'), ('已完成', '已完成')], default='', max_length=512, verbose_name='学习状态')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='学习时间')),
            ],
            options={
                'verbose_name': '课程学习',
                'verbose_name_plural': '课程学习',
                'db_table': 'kechengxuexi',
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='学习进度')),
                ('status', models.CharField(choices=[('待学习', '待学习'), ('学习中', '学习中'), ('已完成', '已完成')], default='待学习', max_length=50, verbose_name='学习状态')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='kechengxuexi.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '课程进度',
                'verbose_name_plural': '课程进度',
                'db_table': 'course_progress',
                'unique_together': {('course', 'student')},
            },
        ),
    ]
