# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiwenneirong', models.CharField(default='', max_length=255, verbose_name='提问内容')),
                ('jiansuoleixing', models.CharField(choices=[('精准', '精准'), ('模糊', '模糊')], default='', max_length=512, verbose_name='检索类型')),
            ],
            options={
                'verbose_name': '问答',
                'verbose_name_plural': '问答',
                'db_table': 'wenda',
            },
        ),
    ]
