# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kechengxuexi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='作业标题')),
                ('content', models.TextField(verbose_name='作业内容')),
                ('type', models.CharField(default='homework', max_length=50, verbose_name='作业类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='kechengxuexi.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='Tijiaozuoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buzhizuoyeid', models.IntegerField(default=0, verbose_name='布置作业id')),
                ('kechengbianhao', models.CharField(default='', max_length=50, verbose_name='课程编号')),
                ('kechengmingcheng', models.CharField(default='', max_length=255, verbose_name='课程名称')),
                ('kechengfenlei', models.IntegerField(default=0, verbose_name='课程分类')),
                ('fabujiaoshi', models.CharField(db_column='fabujiaoshi', default='', max_length=50, verbose_name='发布教师')),
                ('zuoyebianhao', models.CharField(default='', max_length=50, verbose_name='作业编号')),
                ('zuoyemingcheng', models.CharField(default='', max_length=255, verbose_name='作业名称')),
                ('zuoyefujian', models.CharField(default='', max_length=255, verbose_name='作业附件')),
                ('xueshengxingming', models.CharField(default='', max_length=50, verbose_name='学生姓名')),
                ('zuoyezhuangtai', models.CharField(default='', max_length=50, verbose_name='作业状态')),
                ('tijiaoxuesheng', models.CharField(db_column='tijiaoxuesheng', default='', max_length=50, verbose_name='提交学生')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '提交作业',
                'verbose_name_plural': '提交作业',
                'db_table': 'tijiaozuoye',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='答案')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='分数')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='反馈')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tijiaozuoye.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'db_table': 'homework_submission',
            },
        ),
    ]
