# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoucang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', default='', max_length=50, verbose_name='用户')),
                ('xwid', models.IntegerField(default=0, verbose_name='关联表id')),
                ('biao', models.CharField(default='', max_length=50, verbose_name='关联表')),
                ('biaoti', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'shoucang',
            },
        ),
    ]
