# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luntanjiaoliu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.CharField(default='', max_length=50, verbose_name='编号')),
                ('biaoti', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('fenlei', models.IntegerField(default=0, verbose_name='分类')),
                ('tupian', models.CharField(default='', max_length=255, verbose_name='图片')),
                ('huifushu', models.IntegerField(default=0, verbose_name='回复数')),
                ('faburen', models.CharField(db_column='faburen', default='', max_length=50, verbose_name='发布人')),
                ('hudongneirong', models.TextField(default='', verbose_name='互动内容')),
                ('quanxian', models.CharField(default='', max_length=50, verbose_name='权限')),
                ('xingming', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('touxiang', models.CharField(default='', max_length=255, verbose_name='头像')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('issh', models.CharField(default='否', max_length=10, verbose_name='是否审核')),
            ],
            options={
                'verbose_name': '论坛交流',
                'verbose_name_plural': '论坛交流',
                'db_table': 'luntanjiaoliu',
            },
        ),
    ]
