# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xuexijilu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kechengshipinid', models.IntegerField(default=0, verbose_name='课程视频id')),
                ('kechengbianhao', models.CharField(default='', max_length=50, verbose_name='课程编号')),
                ('kechengmingcheng', models.CharField(default='', max_length=255, verbose_name='课程名称')),
                ('kechengfenlei', models.IntegerField(default=0, verbose_name='课程分类')),
                ('fabujiaoshi', models.CharField(db_column='fabujiaoshi', default='', max_length=50, verbose_name='发布教师')),
                ('shipinmingcheng', models.CharField(default='', max_length=255, verbose_name='视频名称')),
                ('xueshengyonghu', models.CharField(db_column='xueshengyonghu', default='', max_length=50, verbose_name='学生用户')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='学习时间')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'db_table': 'xuexijilu',
            },
        ),
    ]
