# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kechengziyuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kechengxinxiid', models.IntegerField(default=0, verbose_name='课程信息id')),
                ('kechengbianhao', models.CharField(default='', max_length=50, verbose_name='课程编号')),
                ('kechengmingcheng', models.CharField(default='', max_length=255, verbose_name='课程名称')),
                ('kechengfenlei', models.IntegerField(default=0, verbose_name='课程分类')),
                ('fabujiaoshi', models.CharField(db_column='fabujiaoshi', default='', max_length=50, verbose_name='发布教师')),
                ('ziyuanmingcheng', models.CharField(default='', max_length=255, verbose_name='资源名称')),
                ('ziyuanfujian', models.CharField(default='', max_length=255, verbose_name='资源附件')),
                ('ziyuanshuoming', models.TextField(default='', verbose_name='资源说明')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
                'db_table': 'kechengziyuan',
            },
        ),
    ]
