# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buzhizuoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kechengxinxiid', models.IntegerField(default=0, verbose_name='课程信息id')),
                ('kechengbianhao', models.CharField(default='', max_length=50, verbose_name='课程编号')),
                ('kechengmingcheng', models.CharField(default='', max_length=255, verbose_name='课程名称')),
                ('kechengfenlei', models.IntegerField(default=0, verbose_name='课程分类')),
                ('fabujiaoshi', models.CharField(db_column='fabujiaoshi', default='', max_length=50, verbose_name='发布教师')),
                ('zuoyebianhao', models.CharField(default='', max_length=50, verbose_name='作业编号')),
                ('jiezhiriqi', models.CharField(default='', max_length=19, verbose_name='截至日期')),
                ('zuoyemingcheng', models.CharField(default='', max_length=255, verbose_name='作业名称')),
                ('zuoyefujian', models.CharField(default='', max_length=255, verbose_name='作业附件')),
                ('yitijiaorenshu', models.IntegerField(default=0, verbose_name='已提交人数')),
                ('zuoyemiaoshu', models.TextField(default='', verbose_name='作业描述')),
            ],
            options={
                'verbose_name': '布置作业',
                'verbose_name_plural': '布置作业',
                'db_table': 'buzhizuoye',
            },
        ),
    ]
