# Generated by Django 3.2.24 on 2025-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzhizuoye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzhizuoye',
            name='fabujiaoshi',
            field=models.CharField(max_length=50, verbose_name='发布教师'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='jiezhiriqi',
            field=models.CharField(max_length=50, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='kechengbianhao',
            field=models.CharField(max_length=50, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='kechengfenlei',
            field=models.IntegerField(verbose_name='课程分类'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='kechengmingcheng',
            field=models.CharField(max_length=50, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='kechengxinxiid',
            field=models.IntegerField(verbose_name='课程信息ID'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='yitijiaorenshu',
            field=models.IntegerField(verbose_name='已提交人数'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='zuoyebianhao',
            field=models.CharField(max_length=50, verbose_name='作业编号'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='zuoyefujian',
            field=models.CharField(max_length=50, verbose_name='作业附件'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='zuoyemiaoshu',
            field=models.TextField(verbose_name='作业描述'),
        ),
        migrations.AlterField(
            model_name='buzhizuoye',
            name='zuoyemingcheng',
            field=models.CharField(max_length=50, verbose_name='作业名称'),
        ),
    ]
