# Generated by Django 3.2.24 on 2025-05-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzhizuoye', '0002_auto_20250512_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzhizuoye',
            name='zuoyefujian',
            field=models.CharField(max_length=255, verbose_name='作业附件'),
        ),
    ]
