# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siliao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.CharField(default='', max_length=50, verbose_name='编号')),
                ('shouxinren', models.CharField(db_column='shouxinren', default='', max_length=50, verbose_name='收信人')),
                ('faxinren', models.CharField(db_column='faxinren', default='', max_length=50, verbose_name='发信人')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='消息最后时间')),
            ],
            options={
                'verbose_name': '私聊',
                'verbose_name_plural': '私聊',
                'db_table': 'siliao',
            },
        ),
    ]
