# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zuoyepiyue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tijiaozuoyeid', models.IntegerField(default=0, verbose_name='提交作业id')),
                ('kechengbianhao', models.CharField(default='', max_length=50, verbose_name='课程编号')),
                ('kechengmingcheng', models.CharField(default='', max_length=255, verbose_name='课程名称')),
                ('kechengfenlei', models.IntegerField(default=0, verbose_name='课程分类')),
                ('fabujiaoshi', models.CharField(db_column='fabujiaoshi', default='', max_length=50, verbose_name='发布教师')),
                ('zuoyemingcheng', models.CharField(default='', max_length=255, verbose_name='作业名称')),
                ('zuoyefujian', models.CharField(default='', max_length=255, verbose_name='作业附件')),
                ('xueshengxingming', models.CharField(default='', max_length=50, verbose_name='学生姓名')),
                ('tijiaoxuesheng', models.CharField(db_column='tijiaoxuesheng', default='', max_length=50, verbose_name='提交学生')),
                ('fenshu', models.IntegerField(default=0, verbose_name='分数')),
                ('pingyu', models.TextField(default='', verbose_name='评语')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='批阅时间')),
            ],
            options={
                'verbose_name': '作业批阅',
                'verbose_name_plural': '作业批阅',
                'db_table': 'zuoyepiyue',
            },
        ),
    ]
