# Generated by Django 3.2.24 on 2025-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admins',
            name='xingbie',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='', max_length=2, verbose_name='性别'),
        ),
    ]
