# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lunbotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('image', models.CharField(default='', max_length=255, verbose_name='图片')),
                ('url', models.CharField(default='', max_length=255, verbose_name='连接地址')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'lunbotu',
            },
        ),
    ]
