# Generated by Django 3.2.24 on 2025-05-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wendaxiaoxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaoxineirong', models.TextField(default='', verbose_name='消息内容')),
                ('huifuneirong', models.TextField(default='', verbose_name='回复内容')),
                ('guanlianhuifu', models.IntegerField(default=0, verbose_name='关联回复')),
                ('yonghu', models.CharField(db_column='yonghu', default='', max_length=50, verbose_name='用户')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '问答消息',
                'verbose_name_plural': '问答消息',
                'db_table': 'wendaxiaoxi',
            },
        ),
    ]
